---
AWSTemplateFormatVersion: 2010-09-09
Description: '[Lab-Archi-Task1] Template which builds VPC, supporting resources, a
  basic networking structure, and some Security groups for use in later tasks.'
Parameters:
  StudentLabTrigram:
    Description: Your unique 3-letter trigram for this course (all lowercase) e.g. tel
    Type: String
    MinLength: 3
    MaxLength: 3
    AllowedPattern: '^[a-z]{3}$'
    ConstraintDescription: Must be exactly 3 lowercase letters

  VPCCIDR:
    Description: CIDR Block for VPC
    Type: String
    Default: 10.100.0.0/16

  PublicSubnet1Param:
    Description: Public Subnet 1
    Type: String
    Default: 10.100.0.0/24
  PublicSubnet2Param:
    Description: Public Subnet 2
    Type: String
    Default: 10.100.1.0/24

  AppSubnet1Param:
    Description: App Subnet 1
    Type: String
    Default: 10.100.2.0/24
  AppSubnet2Param:
    Description: App Subnet 2
    Type: String
    Default: 10.100.3.0/24

  DatabaseSubnet1Param:
    Description: Database Subnet 1
    Type: String
    Default: 10.100.4.0/24
  DatabaseSubnet2Param:
    Description: Database Subnet 2
    Type: String
    Default: 10.100.5.0/24
Resources:
  LabVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCIDR
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-LabVPC'
  LabInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-igw'
  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref LabVPC
      InternetGatewayId: !Ref LabInternetGateway
  NATGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIPAddress1.AllocationId
      SubnetId: !Ref PublicSubnet1
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-natgw-1'
  ElasticIPAddress1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-eip-1'
  NATGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt ElasticIPAddress2.AllocationId
      SubnetId: !Ref PublicSubnet2
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-natgw-2'
  ElasticIPAddress2:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-eip-2'
  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LabVPC
      CidrBlock: !Ref PublicSubnet1Param
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - "0"
        - !GetAZs ""
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-PublicSubnet-1'
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LabVPC
      CidrBlock: !Ref PublicSubnet2Param
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select
        - "1"
        - !GetAZs ""
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-PublicSubnet-2'
  AppSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LabVPC
      CidrBlock: !Ref AppSubnet1Param
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select
        - "0"
        - !GetAZs ""
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-AppSubnet-1'
  AppSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LabVPC
      CidrBlock: !Ref AppSubnet2Param
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select
        - "1"
        - !GetAZs ""
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-AppSubnet-2'
  DatabaseSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LabVPC
      CidrBlock: !Ref DatabaseSubnet1Param
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select
        - "0"
        - !GetAZs ""
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-DatabaseSubnet-1'
  DatabaseSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref LabVPC
      CidrBlock: !Ref DatabaseSubnet2Param
      MapPublicIpOnLaunch: false
      AvailabilityZone: !Select
        - "1"
        - !GetAZs ""
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-DatabaseSubnet-2'
  PublicRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref LabVPC
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-PublicRouteTable'
  PrivateRouteTableAZ1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref LabVPC
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-PrivateRouteTable-AZ1'
  PrivateRouteTableAZ2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref LabVPC
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-PrivateRouteTable-AZ2'
              
  PublicRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PublicRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref LabInternetGateway
  PrivateRouteAZ1:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTableAZ1
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway1
  PrivateRouteAZ2:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref PrivateRouteTableAZ2
      DestinationCidrBlock: 0.0.0.0/0
      NatGatewayId: !Ref NATGateway2
  PublicSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet1
      RouteTableId: !Ref PublicRouteTable
  PublicSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref PublicSubnet2
      RouteTableId: !Ref PublicRouteTable
  AppSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AppSubnet1
      RouteTableId: !Ref PrivateRouteTableAZ1
  AppSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref AppSubnet2
      RouteTableId: !Ref PrivateRouteTableAZ2
  DatabaseSubnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DatabaseSubnet1
      RouteTableId: !Ref PrivateRouteTableAZ1
  DatabaseSubnet2RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref DatabaseSubnet2
      RouteTableId: !Ref PrivateRouteTableAZ2
  AppInstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group allowing HTTP traffic for lab instances
      VpcId: !Ref LabVPC
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-AppInstanceSecurityGroup'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  RDSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group allowing RDS instances to have internet traffic
      VpcId: !Ref LabVPC
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-RDSSecurityGroup'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId: !Ref AppInstanceSecurityGroup
  EFSMountTargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group allowing traffic between EFS Mount Targets and
        Amazon EC2 instances
      VpcId: !Ref LabVPC
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-EFSMountTargetSecurityGroup'
      SecurityGroupIngress:
        - IpProtocol: tcp
          SourceSecurityGroupId: !Ref AppInstanceSecurityGroup
          FromPort: 80
          ToPort: 80
  DatabaseSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS Aurora cluster
      SubnetIds:
        - !Ref DatabaseSubnet1
        - !Ref DatabaseSubnet2
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-db-subnet-group'
  AuroraCluster:
    Type: AWS::RDS::DBCluster
    Properties:
      DBClusterIdentifier: !Join
        - ''
        - - !Ref StudentLabTrigram
          - '-aurora-cluster'
      Engine: aurora-mysql
      DatabaseName: WPDatabase
      MasterUsername: admin
      MasterUserPassword: 'LabPassword123!'
      DBSubnetGroupName: !Ref DatabaseSubnetGroup
      VpcSecurityGroupIds:
        - !Ref RDSSecurityGroup
      StorageEncrypted: false
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-aurora-cluster'
  AuroraInstance1:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Join
        - ''
        - - !Ref StudentLabTrigram
          - '-aurora-instance-1'
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.t3.medium
      Engine: aurora-mysql
      MonitoringInterval: 0
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-aurora-instance-1'
  AuroraReadReplica:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: !Join
        - ''
        - - !Ref StudentLabTrigram
          - '-aurora-read-replica'
      DBClusterIdentifier: !Ref AuroraCluster
      DBInstanceClass: db.t3.medium
      Engine: aurora-mysql
      Tags:
        - Key: Name
          Value: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-aurora-read-replica'
Outputs:
  Region:
    Description: Lab Region
    Value: !Ref AWS::Region
  DatabaseSubnet1CIDR:
    Description: CIDR block for the DB Subnet in AZ a
    Value: !Ref DatabaseSubnet1Param
  DatabaseSubnet2CIDR:
    Description: CIDR block for the DB Subnet in AZ b
    Value: !Ref DatabaseSubnet2Param
  DatabaseSubnet1ID:
    Description: The Subnet ID for the DB Subnet in AZ a
    Value: !Ref DatabaseSubnet1
    Export:
      Name: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-DatabaseSubnet1-ID'
  DatabaseSubnet2ID:
    Description: The Subnet ID for the DB Subnet in AZ b
    Value: !Ref DatabaseSubnet2
    Export:
      Name: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-DatabaseSubnet2-ID'
  AppInstanceSecurityGroupID:
    Description: The Security Group ID for the Lab Instance Security Group
    Value: !Ref AppInstanceSecurityGroup
    Export:
      Name: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-AppInstanceSecurityGroup-ID'
  EFSMountTargetSecurityGroupID:
    Description: The Security Group ID for the Lab EFS Mount Target
    Value: !Ref EFSMountTargetSecurityGroup
    Export:
      Name: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-EFSMountTargetSecurityGroup-ID'  
  RDSSecurityGroupID:
    Description: The Security Group ID for the Lab RDS cluster
    Value: !Ref RDSSecurityGroup
    Export:
      Name: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-RDSSecurityGroup-ID'
  VPCID:
    Description: The VPC ID for the lab
    Value: !Ref LabVPC
    Export:
      Name: !Join
            - ''
            - - !Ref StudentLabTrigram
              - '-VPC-ID'
  AuroraMasterUsername:
    Description: The master username for the Aurora cluster
    Value: admin
  AuroraMasterUserPassword:
    Description: The master user password for the Aurora cluster
    Value: 'LabPassword123!'
  AuroraClusterEndpoint:
    Description: The Aurora cluster write endpoint
    Value: !GetAtt AuroraCluster.Endpoint.Address
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      - 
        Label: 
          default: "Global"
        Parameters: 
          - StudentLabTrigram
          - VPCCIDR
      - 
        Label: 
          default: "Public Subnets"
        Parameters: 
          - PublicSubnet1Param
          - PublicSubnet2Param
      - 
        Label: 
          default: "Private Subnets"
        Parameters: 
          - AppSubnet1Param
          - AppSubnet2Param
          - DatabaseSubnet1Param
          - DatabaseSubnet2Param